### ISSUE TITLE
Display items - Cursor selection is off by half a pixel

### ISSUE THREAD

**Issue by Ion-e** [Phasefocus/nionswift#16]
Seen whilst working on the Zoom tool,
@Tiomat85 would you mind adding any more information about the issue?

**Comment by jamesrussell216** [comment]
@Ion-e as we're moving our Kanban board to Nion internal, this issue needs reporting under some appropriate Nion repro Jonny. Can you do that so I can then erase it from here plz?

**Comment by Ion-e** [comment]
Done, closing issue as per comment and resolution.
