### ISSUE TITLE
Software freezes when doing post processing

### ISSUE THREAD

**Issue by Ion-e** [Phasefocus/nionswift#19]
I have found myself in different occassions with the software fully frozen, although the PC and other apps in it still run smoothly.

"If a large processing is going to take place, I want it to be done in the background so my I don't wait time waiting for it."

**Comment by jamesrussell216** [comment]
When you say frozen @Ion-e do you mean Windows "not responding" or just stuck (as if it was a static image)? Can you document some examples for reference plz?

**Comment by Ion-e** [comment]
Yes, if you go to image 1,
![image](https://github.com/Phasefocus/nionswift/assets/19330696/fd5ff1a1-983f-4d23-b919-d96d4e69e56c)
Select a data item that has a large amount of pixels > Under "Inspector" in the Image Display change "Default" to "Line plot" < The mouse cursor keeps spinning, any interaction with the software will make it go "unresposive".
More so, it seems that interacting with the generated line plot will noticeably slow the software.

Please observe in image 2, the usage of components doesn't seem over the top, however please note that the used PC has low specs compared to the expected specs.
![image](https://github.com/Phasefocus/nionswift/assets/19330696/309d63f7-79f9-4ff4-9eec-e9de15a679e1)

@jamesrussell216, sorry I think I should have responded to your thread but have created a new one, here be the example.
