### ISSUE TITLE
586 - Export batch with no boxes checked overwrites same file repeatedly

### ISSUE THREAD

**Issue by jamesrussell216** [Phasefocus/nionswift#6]
https://github.com/nion-software/nionswift/issues/586

**Comment by Tiomat85** [comment]
So attempting to define a spec here:

Prefix_Title_Date_Dimension_Sequence.png is what is currently used.  This does not handle situations where there is no Title value (you get the '_' still.  If no optiuons are selected, all filenames are equivalent and so it overwrites constantly. If there are existing files, it overwrites.

New spec:
Filename built up as combination of strings still, in the same order with the extra addition of a 'duplicate suffix'.  Duplicate suffix is defined as a string, including a $, where $ is replaced with an incrementing number where duplicate file names are included.  If the duplicate suffix is not defined, the file will be overwritten.
Blank entries should be excluded, and not include their trailing underscores.

**Comment by jamesrussell216** [comment]
This works. Just to be explicit, there are two requirements here.
- In the batch export wizard, if a field is included (ticked/checked) in the filename, but that field is blank (e.g. the Title field is blank/empty), currently you'd get a filename starting with an underscore. This is probably not what the user intends, so in event of a blank field, the software should behave as if that option had not been checked.
- And 2, adopting the standard Windows (##) behaviour when a file name conflict arises, not overwriting the file.
