### ISSUE TITLE
Missing Workspace Controller

### ISSUE THREAD

**Issue by Tiomat85** [Phasefocus/nionswift#7]
Select a Data Item on the left Data Panel
Press 'Split Panel into Left and Right'
See error thrown at the bottom: 
File "C:\NionApps\Developer\main\nionswift\nion\swift\DocumentController.py", line 3497, in execute
    raise ValueError("Missing workspace controller")
ValueError: Missing workspace controller

**Comment by jamesrussell216** [comment]
@Tiomat85 you having an argument with Github automation?
